# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: 'npm install'
  displayName: 'Install'
  
- script: 'npm run ts-test'
  displayName: 'Test'

- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '3c25275a-7adf-43f1-9b7a-7347d4f4b194'

