# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: '9f63ea7a-8eba-4d9c-a3bb-a09abfad20a8'
  
- script: 'npm run ts-test'
  displayName: 'Test'

- task: CmdLine@2
  inputs:
    script: 'rm -R node_modules && rm -R .git'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'cognitive-face-js'
    publishLocation: 'Container'

