# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: 'npm install'
  displayName: 'Install'
  
#- script: 'npm run ts-test'
#  displayName: 'Test'

- script: 'npm run compile'
  displayName: 'Compile'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: './dist/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'https://pkgs.dev.azure.com/allincloudservices/_packaging/Artifacts/npm/:_password=eGNvbTViYjUzY3plZTNleHo1a3F1NG9pMmlubDM1cXR0cnNoYWRwbjRvYjIydWt5Z2FxYQ=='

#- task: AzureFileCopy@3
#  inputs:
#    SourcePath: './dist/$(Build.BuildId).zip'
#    azureSubscription: 'Visual Studio Enterprise (1c86dc94-8e3e-4987-9835-1e8fa91876a9)'
#    Destination: 'AzureBlob'
#    storage: 'rdomingo1986'
#    ContainerName: 'dbbackups'
